apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: alertmanager
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    replicaCount: 2
